sudo: required
services:
  - docker

before_install:
  - docker build -t cgriffith-4243/tile-game -f Dockerfile.dev .


script:
  - docker run -e CI=true cgriffith-4243/tile-game npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-278733599482"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY”