sudo: required
services:
  - docker

before_install:
  - docker build -t cgriffith4243/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cgriffith4243/tile-game npm run test -- --coverage
