sudo: required
services:
  - docker

before_install:
  - docker build -t cgriffith-4243/tile-game -f Dockerfile.dev .


script:
  - docker run -e CI=true cgriffith-4243/tile-game npm run test -- --coverage